version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16 # Use the Node.js version you're using
    commands:
      - npm install
  build:
    commands:
      - npm run build # Replace with your build command if necessary
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'

